id: P1DF6AA5D
initial_creation_type: input
source_metadata:
  title: Nyoshul Khenpo Jamyang Dorje
  language: fr
  description: 'Texts by the great Dzogchen teacher and historian Nyoshul Khenpo Jamyang
    Dorje (smyo shul mkhan po ''jam dbyangs rdo rje, 1932–1999):'
  volume:
    7bf256951b1d4d03a7e928432e1caf0b:
      title: 'Luminous Clouds of Spontaneous Song: A Prayer to Call the Guru from
        Afar'
      parent: Calling the Guru from Afar
    ccb5d9b476e74360bfb519c5a3f2cd01:
      title: Advice in a Single Statement (from Khenpo Ngawang Palzang)
      parent: Dzogchen
    974c18060b374186b2a44b6a62a8528f:
      title: Principles of the Dzogchen Practice of Khordé Rushen
      parent: Dzogchen
    4ba4413c80a44c23929c5a63c159a8f8:
      title: The Five Wisdoms
      parent: Dzogchen
    0628436d36db485ba52fb650009333d8:
      title: Prayer to the Omniscient Longchen Rabjam
      parent: Lineage Prayers
    ac40873d2a184e7baac86e17effe6305:
      title: 'Mindfulness: The Mirror of the Mind'
      parent: Poems
    069fbe099ac84c4ebd68371a97ea8378:
      title: Natural Great Peace
      parent: Poems
created_at: '2022-03-01T01:05:41.716940'
last_modified_at: '2022-03-01T01:05:41.716943'
